let response = {
    from: 1,
    to: 6,
    count: 6,
    _links: {},
    hits: [
        {
            recipe: {
                uri: "http://www.edamam.com/ontologies/edamam.owl#recipe_753c111cf320a1e51d1ff36763c0d1c3",
                label: "Shrimp Scampi Alfredo",
                image: "https://edamam-product-images.s3.amazonaws.com/web-img/02d/02dad41a16a086a98cfae3ac05a5047f.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQD58OvaS0k1th1eieaHIvo%2BArqS3ctqottfA67g9NJDiwIgfCjiMNbdDnrYyYvmLcgV93ti%2BWhrZtGP1qIO8XOqvrsq2wQI3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDA%2FsXz09Olo%2F8duILiqvBMnGnHQQDHJeTEaSlJjgs9FSxWnHZOfDij%2BgSaQdpBifykRxbIMgBoe%2F3O6cMSt504QCj6XfTWjQNt9eQyz2QF9dwxAJCp0PPFR1s0SiUmy%2FozQMeXyNNtoxE6NYN0EDf07cmfkdJLpUWw2ppdPBCXVBTwmsfJn%2Fh6JPWG9Ac8MadagCC40I22QBUFpKxfu%2BEVRGJXPFvwgM8dXocsStgASDigBBdD4KPdwmTt3nh37Ad%2FNFrXRyI5D4bqX4AxsqH4Iw%2By4LRJWdVFggV%2FzFKgPO6%2BAI6BMdugcEqjAS40w%2BbkxOY%2BNJl78Kh7ifecMkl8Fb%2Fnm6LYsldRpQsk1fK9r14D65%2BBEICt4b5UFg4QVcZAeSIm2xNLrLP63WZB1uply3A1GNXgxLPVPWAfz7O4obTy8xeQyPH46dbKWROz0WIurT2jiJITANLgvWWLl1gpgVo0Lv8%2BiLCt3Y05cf5XUFFg3IZJBCFKhGBy5WDRhONBBWOh3zFgnvtUmIiSxn3cSEUU8vBbMjgUPhdkHYKs%2BFDg%2BXhJlGpfEcdWuWzufnur5F9As7kapxYEXzwUEVNFbmMh8depJ%2FgiprNq6xwj0c%2BIO%2F7LGYVjeJ3IGG4jxDeFk%2FFktO93zk4maQnJ%2FgT23wi8Dnrrs%2F8a5Pi7m6qfrrIUr0K9V9UHX6LmQpcEHem7rJ%2BoM8MyH2x7XE6DBxoqQN3bGfY%2FSccYsScLlpFGLCr%2BSuvUX%2FcR7Me3HYKFEwj4G7lwY6qQF3%2FMB1mRqpoEQJ3tycVR%2Bdy4x4ixzjVLs%2B0uHjiI9I209eYWcOouy%2B9A2bGrszT2wjns%2Fn3u9W62EsgSoV%2FgNZMRQjkLtz2tuRGa9ZrHwIa0yAW7x9NKA%2BK%2BYSvIr%2FILrxbQvgs2b%2B8L8bFUiHl%2FFxzTXIFhVda0DKdY%2FUBVNxbNafHk6q8cCvC2J%2FiTsYlexx19skpkvx%2F6VkzBmzgvZzDeJKOCSP9i%2BA&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220806T200841Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFE64WOM3J%2F20220806%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7b477d91442f7a9e3c0be93121364ec3d6dc7c3654e1b6f2d425b78a879a98fc",
                images: {
                    THUMBNAIL: {
                        url: "https://edamam-product-images.s3.amazonaws.com/web-img/02d/02dad41a16a086a98cfae3ac05a5047f-s.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQD58OvaS0k1th1eieaHIvo%2BArqS3ctqottfA67g9NJDiwIgfCjiMNbdDnrYyYvmLcgV93ti%2BWhrZtGP1qIO8XOqvrsq2wQI3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDA%2FsXz09Olo%2F8duILiqvBMnGnHQQDHJeTEaSlJjgs9FSxWnHZOfDij%2BgSaQdpBifykRxbIMgBoe%2F3O6cMSt504QCj6XfTWjQNt9eQyz2QF9dwxAJCp0PPFR1s0SiUmy%2FozQMeXyNNtoxE6NYN0EDf07cmfkdJLpUWw2ppdPBCXVBTwmsfJn%2Fh6JPWG9Ac8MadagCC40I22QBUFpKxfu%2BEVRGJXPFvwgM8dXocsStgASDigBBdD4KPdwmTt3nh37Ad%2FNFrXRyI5D4bqX4AxsqH4Iw%2By4LRJWdVFggV%2FzFKgPO6%2BAI6BMdugcEqjAS40w%2BbkxOY%2BNJl78Kh7ifecMkl8Fb%2Fnm6LYsldRpQsk1fK9r14D65%2BBEICt4b5UFg4QVcZAeSIm2xNLrLP63WZB1uply3A1GNXgxLPVPWAfz7O4obTy8xeQyPH46dbKWROz0WIurT2jiJITANLgvWWLl1gpgVo0Lv8%2BiLCt3Y05cf5XUFFg3IZJBCFKhGBy5WDRhONBBWOh3zFgnvtUmIiSxn3cSEUU8vBbMjgUPhdkHYKs%2BFDg%2BXhJlGpfEcdWuWzufnur5F9As7kapxYEXzwUEVNFbmMh8depJ%2FgiprNq6xwj0c%2BIO%2F7LGYVjeJ3IGG4jxDeFk%2FFktO93zk4maQnJ%2FgT23wi8Dnrrs%2F8a5Pi7m6qfrrIUr0K9V9UHX6LmQpcEHem7rJ%2BoM8MyH2x7XE6DBxoqQN3bGfY%2FSccYsScLlpFGLCr%2BSuvUX%2FcR7Me3HYKFEwj4G7lwY6qQF3%2FMB1mRqpoEQJ3tycVR%2Bdy4x4ixzjVLs%2B0uHjiI9I209eYWcOouy%2B9A2bGrszT2wjns%2Fn3u9W62EsgSoV%2FgNZMRQjkLtz2tuRGa9ZrHwIa0yAW7x9NKA%2BK%2BYSvIr%2FILrxbQvgs2b%2B8L8bFUiHl%2FFxzTXIFhVda0DKdY%2FUBVNxbNafHk6q8cCvC2J%2FiTsYlexx19skpkvx%2F6VkzBmzgvZzDeJKOCSP9i%2BA&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220806T200841Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFE64WOM3J%2F20220806%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=094086828f0c4ae67e8f520429a63acf1fbd4bd55c434f811ba19212b38a06f3",
                        width: 100,
                        height: 100,
                    },
                    SMALL: {
                        url: "https://edamam-product-images.s3.amazonaws.com/web-img/02d/02dad41a16a086a98cfae3ac05a5047f-m.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQD58OvaS0k1th1eieaHIvo%2BArqS3ctqottfA67g9NJDiwIgfCjiMNbdDnrYyYvmLcgV93ti%2BWhrZtGP1qIO8XOqvrsq2wQI3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDA%2FsXz09Olo%2F8duILiqvBMnGnHQQDHJeTEaSlJjgs9FSxWnHZOfDij%2BgSaQdpBifykRxbIMgBoe%2F3O6cMSt504QCj6XfTWjQNt9eQyz2QF9dwxAJCp0PPFR1s0SiUmy%2FozQMeXyNNtoxE6NYN0EDf07cmfkdJLpUWw2ppdPBCXVBTwmsfJn%2Fh6JPWG9Ac8MadagCC40I22QBUFpKxfu%2BEVRGJXPFvwgM8dXocsStgASDigBBdD4KPdwmTt3nh37Ad%2FNFrXRyI5D4bqX4AxsqH4Iw%2By4LRJWdVFggV%2FzFKgPO6%2BAI6BMdugcEqjAS40w%2BbkxOY%2BNJl78Kh7ifecMkl8Fb%2Fnm6LYsldRpQsk1fK9r14D65%2BBEICt4b5UFg4QVcZAeSIm2xNLrLP63WZB1uply3A1GNXgxLPVPWAfz7O4obTy8xeQyPH46dbKWROz0WIurT2jiJITANLgvWWLl1gpgVo0Lv8%2BiLCt3Y05cf5XUFFg3IZJBCFKhGBy5WDRhONBBWOh3zFgnvtUmIiSxn3cSEUU8vBbMjgUPhdkHYKs%2BFDg%2BXhJlGpfEcdWuWzufnur5F9As7kapxYEXzwUEVNFbmMh8depJ%2FgiprNq6xwj0c%2BIO%2F7LGYVjeJ3IGG4jxDeFk%2FFktO93zk4maQnJ%2FgT23wi8Dnrrs%2F8a5Pi7m6qfrrIUr0K9V9UHX6LmQpcEHem7rJ%2BoM8MyH2x7XE6DBxoqQN3bGfY%2FSccYsScLlpFGLCr%2BSuvUX%2FcR7Me3HYKFEwj4G7lwY6qQF3%2FMB1mRqpoEQJ3tycVR%2Bdy4x4ixzjVLs%2B0uHjiI9I209eYWcOouy%2B9A2bGrszT2wjns%2Fn3u9W62EsgSoV%2FgNZMRQjkLtz2tuRGa9ZrHwIa0yAW7x9NKA%2BK%2BYSvIr%2FILrxbQvgs2b%2B8L8bFUiHl%2FFxzTXIFhVda0DKdY%2FUBVNxbNafHk6q8cCvC2J%2FiTsYlexx19skpkvx%2F6VkzBmzgvZzDeJKOCSP9i%2BA&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220806T200841Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFE64WOM3J%2F20220806%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=fd75ed550b18df8cb646723fcca9cd265ef43a48392876a6a59654aea8b676f4",
                        width: 200,
                        height: 200,
                    },
                    REGULAR: {
                        url: "https://edamam-product-images.s3.amazonaws.com/web-img/02d/02dad41a16a086a98cfae3ac05a5047f.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQD58OvaS0k1th1eieaHIvo%2BArqS3ctqottfA67g9NJDiwIgfCjiMNbdDnrYyYvmLcgV93ti%2BWhrZtGP1qIO8XOqvrsq2wQI3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDA%2FsXz09Olo%2F8duILiqvBMnGnHQQDHJeTEaSlJjgs9FSxWnHZOfDij%2BgSaQdpBifykRxbIMgBoe%2F3O6cMSt504QCj6XfTWjQNt9eQyz2QF9dwxAJCp0PPFR1s0SiUmy%2FozQMeXyNNtoxE6NYN0EDf07cmfkdJLpUWw2ppdPBCXVBTwmsfJn%2Fh6JPWG9Ac8MadagCC40I22QBUFpKxfu%2BEVRGJXPFvwgM8dXocsStgASDigBBdD4KPdwmTt3nh37Ad%2FNFrXRyI5D4bqX4AxsqH4Iw%2By4LRJWdVFggV%2FzFKgPO6%2BAI6BMdugcEqjAS40w%2BbkxOY%2BNJl78Kh7ifecMkl8Fb%2Fnm6LYsldRpQsk1fK9r14D65%2BBEICt4b5UFg4QVcZAeSIm2xNLrLP63WZB1uply3A1GNXgxLPVPWAfz7O4obTy8xeQyPH46dbKWROz0WIurT2jiJITANLgvWWLl1gpgVo0Lv8%2BiLCt3Y05cf5XUFFg3IZJBCFKhGBy5WDRhONBBWOh3zFgnvtUmIiSxn3cSEUU8vBbMjgUPhdkHYKs%2BFDg%2BXhJlGpfEcdWuWzufnur5F9As7kapxYEXzwUEVNFbmMh8depJ%2FgiprNq6xwj0c%2BIO%2F7LGYVjeJ3IGG4jxDeFk%2FFktO93zk4maQnJ%2FgT23wi8Dnrrs%2F8a5Pi7m6qfrrIUr0K9V9UHX6LmQpcEHem7rJ%2BoM8MyH2x7XE6DBxoqQN3bGfY%2FSccYsScLlpFGLCr%2BSuvUX%2FcR7Me3HYKFEwj4G7lwY6qQF3%2FMB1mRqpoEQJ3tycVR%2Bdy4x4ixzjVLs%2B0uHjiI9I209eYWcOouy%2B9A2bGrszT2wjns%2Fn3u9W62EsgSoV%2FgNZMRQjkLtz2tuRGa9ZrHwIa0yAW7x9NKA%2BK%2BYSvIr%2FILrxbQvgs2b%2B8L8bFUiHl%2FFxzTXIFhVda0DKdY%2FUBVNxbNafHk6q8cCvC2J%2FiTsYlexx19skpkvx%2F6VkzBmzgvZzDeJKOCSP9i%2BA&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220806T200841Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFE64WOM3J%2F20220806%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7b477d91442f7a9e3c0be93121364ec3d6dc7c3654e1b6f2d425b78a879a98fc",
                        width: 300,
                        height: 300,
                    },
                },
                source: "BigOven",
                url: "http://www.bigoven.com/recipe/Shrimp-Scampi-Alfredo/206350",
                shareAs:
                    "http://www.edamam.com/recipe/shrimp-scampi-alfredo-753c111cf320a1e51d1ff36763c0d1c3/shrimp+scampi+alfredo",
                yield: 8,
                dietLabels: ["Balanced"],
                healthLabels: [
                    "Sugar-Conscious",
                    "Pescatarian",
                    "Egg-Free",
                    "Peanut-Free",
                    "Tree-Nut-Free",
                    "Pork-Free",
                    "Red-Meat-Free",
                    "Celery-Free",
                    "Mustard-Free",
                    "Sesame-Free",
                    "Lupine-Free",
                    "Mollusk-Free",
                    "Alcohol-Free",
                ],
                cautions: ["Soy"],
                ingredientLines: [
                    "16 oz pasta",
                    "1 lb shrimp",
                    "16 oz alfredo sauce",
                    "4 tbsp soy sauce",
                    "1 stick margarine",
                    "2 tbsp garlic",
                    "1 tbsp italian herbs",
                    "1 tsp cajun seasoning",
                    "2 tbsp milk",
                ],
                ingredients: [
                    {
                        text: "16 oz pasta",
                        quantity: 16,
                        measure: "ounce",
                        food: "pasta",
                        weight: 453.59237,
                        foodCategory: "grains",
                        foodId: "food_a8hs60uayl5icia1qe8qoba1kwp8",
                        image: "https://www.edamam.com/food-img/296/296ff2b02ef3822928c3c923e22c7d19.jpg",
                    },
                    {
                        text: "1 lb shrimp",
                        quantity: 1,
                        measure: "pound",
                        food: "shrimp",
                        weight: 453.59237,
                        foodCategory: "seafood",
                        foodId: "food_bjap0xzbf5x6s3azkpwtfb14i25u",
                        image: "https://www.edamam.com/food-img/4df/4df0fd62e878ed84b387b9e3ab48f2dc.jpg",
                    },
                    {
                        text: "16 oz alfredo sauce",
                        quantity: 16,
                        measure: "ounce",
                        food: "alfredo sauce",
                        weight: 453.59237,
                        foodCategory: "condiments and sauces",
                        foodId: "food_b2ayx5tbjhbyviaj61ut3ajui5yu",
                        image: null,
                    },
                    {
                        text: "4 tbsp soy sauce",
                        quantity: 4,
                        measure: "tablespoon",
                        food: "soy sauce",
                        weight: 64,
                        foodCategory: "plant-based protein",
                        foodId: "food_a5g9yevb1iactoaiimbvjbkrxueh",
                        image: "https://www.edamam.com/food-img/f56/f562e461eb0618f367f538b836c17b82.jpg",
                    },
                    {
                        text: "1 stick margarine",
                        quantity: 1,
                        measure: "stick",
                        food: "margarine",
                        weight: 113,
                        foodCategory: "Oils",
                        foodId: "food_bpy417na9x14isbywkw04a21r148",
                        image: "https://www.edamam.com/food-img/33e/33ef6c4bf7db16d574a3f68fa31c4b09.jpg",
                    },
                    {
                        text: "2 tbsp garlic",
                        quantity: 2,
                        measure: "tablespoon",
                        food: "garlic",
                        weight: 16.999999999712582,
                        foodCategory: "vegetables",
                        foodId: "food_avtcmx6bgjv1jvay6s6stan8dnyp",
                        image: "https://www.edamam.com/food-img/6ee/6ee142951f48aaf94f4312409f8d133d.jpg",
                    },
                    {
                        text: "1 tbsp italian herbs",
                        quantity: 1,
                        measure: "tablespoon",
                        food: "herbs",
                        weight: 2.7,
                        foodCategory: "Condiments and sauces",
                        foodId: "food_avsq22zadwyb5cb5sl1byaa4mbo8",
                        image: "https://www.edamam.com/food-img/89b/89b37a04e46e052671d73addcb84aa51.jpg",
                    },
                    {
                        text: "1 tsp cajun seasoning",
                        quantity: 1,
                        measure: "teaspoon",
                        food: "seasoning",
                        weight: 1.5,
                        foodCategory: "Condiments and sauces",
                        foodId: "food_aj7w3xab0epj7cbgkbkpwadysovd",
                        image: "https://www.edamam.com/food-img/c23/c23e20823b442067307aa436969358f1.jpg",
                    },
                    {
                        text: "2 tbsp milk",
                        quantity: 2,
                        measure: "tablespoon",
                        food: "milk",
                        weight: 30,
                        foodCategory: "Milk",
                        foodId: "food_b49rs1kaw0jktabzkg2vvanvvsis",
                        image: "https://www.edamam.com/food-img/7c9/7c9962acf83654a8d98ea6a2ade93735.jpg",
                    },
                ],
                calories: 4181.557796949572,
                totalWeight: 1588.9771099997126,
                totalTime: 45,
                cuisineType: ["mediterranean"],
                mealType: ["lunch/dinner"],
                dishType: ["main course"],
                totalNutrients: {
                    ENERC_KCAL: {
                        label: "Energy",
                        quantity: 4181.557796949572,
                        unit: "kcal",
                    },
                    FAT: {
                        label: "Fat",
                        quantity: 184.54363912149861,
                        unit: "g",
                    },
                    FASAT: {
                        label: "Saturated",
                        quantity: 49.514296341599746,
                        unit: "g",
                    },
                    FATRN: {
                        label: "Trans",
                        quantity: 16.8438436948,
                        unit: "g",
                    },
                    FAMS: {
                        label: "Monounsaturated",
                        quantity: 76.43008291854999,
                        unit: "g",
                    },
                    FAPU: {
                        label: "Polyunsaturated",
                        quantity: 50.5664528976993,
                        unit: "g",
                    },
                    CHOCDF: {
                        label: "Carbs",
                        quantity: 435.24001944090503,
                        unit: "g",
                    },
                    "CHOCDF.net": {
                        label: "Carbohydrates (net)",
                        quantity: 0,
                        unit: "g",
                    },
                    FIBTG: {
                        label: "Fiber",
                        quantity: 21.088379539993966,
                        unit: "g",
                    },
                    SUGAR: {
                        label: "Sugars",
                        quantity: 26.37208026899713,
                        unit: "g",
                    },
                    "SUGAR.added": {
                        label: "Sugars, added",
                        quantity: 0,
                        unit: "g",
                    },
                    PROCNT: {
                        label: "Protein",
                        quantity: 192.87210695998172,
                        unit: "g",
                    },
                    CHOLE: {
                        label: "Cholesterol",
                        quantity: 860.2895793000001,
                        unit: "mg",
                    },
                    NA: {
                        label: "Sodium",
                        quantity: 10713.231653999952,
                        unit: "mg",
                    },
                    CA: {
                        label: "Calcium",
                        quantity: 1599.8416984494802,
                        unit: "mg",
                    },
                    MG: {
                        label: "Magnesium",
                        quantity: 536.7760647999282,
                        unit: "mg",
                    },
                    K: {
                        label: "Potassium",
                        quantity: 3223.805151798848,
                        unit: "mg",
                    },
                    FE: {
                        label: "Iron",
                        quantity: 15.615565272995118,
                        unit: "mg",
                    },
                    ZN: {
                        label: "Zinc",
                        quantity: 17.05631333149667,
                        unit: "mg",
                    },
                    P: {
                        label: "Phosphorus",
                        quantity: 2940.2734188495606,
                        unit: "mg",
                    },
                    VITA_RAE: {
                        label: "Vitamin A",
                        quantity: 143.3799399,
                        unit: "µg",
                    },
                    VITC: {
                        label: "Vitamin C",
                        quantity: 6.833999999910326,
                        unit: "mg",
                    },
                    THIA: {
                        label: "Thiamin (B1)",
                        quantity: 0.8623261815994252,
                        unit: "mg",
                    },
                    RIBF: {
                        label: "Riboflavin (B2)",
                        quantity: 0.583263361899684,
                        unit: "mg",
                    },
                    NIA: {
                        label: "Niacin (B3)",
                        quantity: 14.138211319497989,
                        unit: "mg",
                    },
                    VITB6A: {
                        label: "Vitamin B6",
                        quantity: 1.2981280532964505,
                        unit: "mg",
                    },
                    FOLDFE: {
                        label: "Folate equivalent (total)",
                        quantity: 112.28647399999136,
                        unit: "µg",
                    },
                    FOLFD: {
                        label: "Folate (food)",
                        quantity: 112.28647399999136,
                        unit: "µg",
                    },
                    FOLAC: {
                        label: "Folic acid",
                        quantity: 0,
                        unit: "µg",
                    },
                    VITB12: {
                        label: "Vitamin B12",
                        quantity: 0.9968255030000002,
                        unit: "µg",
                    },
                    VITD: {
                        label: "Vitamin D",
                        quantity: 0.39,
                        unit: "µg",
                    },
                    TOCPHA: {
                        label: "Vitamin E",
                        quantity: 10.838261410999772,
                        unit: "mg",
                    },
                    VITK1: {
                        label: "Vitamin K",
                        quantity: 158.01645583999513,
                        unit: "µg",
                    },
                    "Sugar.alcohol": {
                        label: "Sugar alcohol",
                        quantity: 0,
                        unit: "g",
                    },
                    WATER: {
                        label: "Water",
                        quantity: 506.3493606873317,
                        unit: "g",
                    },
                },
                totalDaily: {
                    ENERC_KCAL: {
                        label: "Energy",
                        quantity: 209.0778898474786,
                        unit: "%",
                    },
                    FAT: {
                        label: "Fat",
                        quantity: 283.9132909561517,
                        unit: "%",
                    },
                    FASAT: {
                        label: "Saturated",
                        quantity: 247.57148170799874,
                        unit: "%",
                    },
                    CHOCDF: {
                        label: "Carbs",
                        quantity: 145.08000648030168,
                        unit: "%",
                    },
                    FIBTG: {
                        label: "Fiber",
                        quantity: 84.35351815997586,
                        unit: "%",
                    },
                    PROCNT: {
                        label: "Protein",
                        quantity: 385.74421391996344,
                        unit: "%",
                    },
                    CHOLE: {
                        label: "Cholesterol",
                        quantity: 286.7631931000001,
                        unit: "%",
                    },
                    NA: {
                        label: "Sodium",
                        quantity: 446.384652249998,
                        unit: "%",
                    },
                    CA: {
                        label: "Calcium",
                        quantity: 159.984169844948,
                        unit: "%",
                    },
                    MG: {
                        label: "Magnesium",
                        quantity: 127.80382495236385,
                        unit: "%",
                    },
                    K: {
                        label: "Potassium",
                        quantity: 68.59159897444357,
                        unit: "%",
                    },
                    FE: {
                        label: "Iron",
                        quantity: 86.75314040552843,
                        unit: "%",
                    },
                    ZN: {
                        label: "Zinc",
                        quantity: 155.057393922697,
                        unit: "%",
                    },
                    P: {
                        label: "Phosphorus",
                        quantity: 420.0390598356515,
                        unit: "%",
                    },
                    VITA_RAE: {
                        label: "Vitamin A",
                        quantity: 15.931104433333335,
                        unit: "%",
                    },
                    VITC: {
                        label: "Vitamin C",
                        quantity: 7.593333333233695,
                        unit: "%",
                    },
                    THIA: {
                        label: "Thiamin (B1)",
                        quantity: 71.86051513328543,
                        unit: "%",
                    },
                    RIBF: {
                        label: "Riboflavin (B2)",
                        quantity: 44.86641245382184,
                        unit: "%",
                    },
                    NIA: {
                        label: "Niacin (B3)",
                        quantity: 88.36382074686243,
                        unit: "%",
                    },
                    VITB6A: {
                        label: "Vitamin B6",
                        quantity: 99.85600409972696,
                        unit: "%",
                    },
                    FOLDFE: {
                        label: "Folate equivalent (total)",
                        quantity: 28.07161849999784,
                        unit: "%",
                    },
                    VITB12: {
                        label: "Vitamin B12",
                        quantity: 41.53439595833334,
                        unit: "%",
                    },
                    VITD: {
                        label: "Vitamin D",
                        quantity: 2.6,
                        unit: "%",
                    },
                    TOCPHA: {
                        label: "Vitamin E",
                        quantity: 72.25507607333181,
                        unit: "%",
                    },
                    VITK1: {
                        label: "Vitamin K",
                        quantity: 131.6803798666626,
                        unit: "%",
                    },
                },
                digest: [
                    {
                        label: "Fat",
                        tag: "FAT",
                        schemaOrgTag: "fatContent",
                        total: 184.54363912149861,
                        hasRDI: true,
                        daily: 283.9132909561517,
                        unit: "g",
                        sub: [
                            {
                                label: "Saturated",
                                tag: "FASAT",
                                schemaOrgTag: "saturatedFatContent",
                                total: 49.514296341599746,
                                hasRDI: true,
                                daily: 247.57148170799874,
                                unit: "g",
                            },
                            {
                                label: "Trans",
                                tag: "FATRN",
                                schemaOrgTag: "transFatContent",
                                total: 16.8438436948,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                            {
                                label: "Monounsaturated",
                                tag: "FAMS",
                                schemaOrgTag: null,
                                total: 76.43008291854999,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                            {
                                label: "Polyunsaturated",
                                tag: "FAPU",
                                schemaOrgTag: null,
                                total: 50.5664528976993,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                        ],
                    },
                    {
                        label: "Carbs",
                        tag: "CHOCDF",
                        schemaOrgTag: "carbohydrateContent",
                        total: 435.24001944090503,
                        hasRDI: true,
                        daily: 145.08000648030168,
                        unit: "g",
                        sub: [
                            {
                                label: "Carbs (net)",
                                tag: "CHOCDF.net",
                                schemaOrgTag: null,
                                total: 0,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                            {
                                label: "Fiber",
                                tag: "FIBTG",
                                schemaOrgTag: "fiberContent",
                                total: 21.088379539993966,
                                hasRDI: true,
                                daily: 84.35351815997586,
                                unit: "g",
                            },
                            {
                                label: "Sugars",
                                tag: "SUGAR",
                                schemaOrgTag: "sugarContent",
                                total: 26.37208026899713,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                            {
                                label: "Sugars, added",
                                tag: "SUGAR.added",
                                schemaOrgTag: null,
                                total: 0,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                        ],
                    },
                    {
                        label: "Protein",
                        tag: "PROCNT",
                        schemaOrgTag: "proteinContent",
                        total: 192.87210695998172,
                        hasRDI: true,
                        daily: 385.74421391996344,
                        unit: "g",
                    },
                    {
                        label: "Cholesterol",
                        tag: "CHOLE",
                        schemaOrgTag: "cholesterolContent",
                        total: 860.2895793000001,
                        hasRDI: true,
                        daily: 286.7631931000001,
                        unit: "mg",
                    },
                    {
                        label: "Sodium",
                        tag: "NA",
                        schemaOrgTag: "sodiumContent",
                        total: 10713.231653999952,
                        hasRDI: true,
                        daily: 446.384652249998,
                        unit: "mg",
                    },
                    {
                        label: "Calcium",
                        tag: "CA",
                        schemaOrgTag: null,
                        total: 1599.8416984494802,
                        hasRDI: true,
                        daily: 159.984169844948,
                        unit: "mg",
                    },
                    {
                        label: "Magnesium",
                        tag: "MG",
                        schemaOrgTag: null,
                        total: 536.7760647999282,
                        hasRDI: true,
                        daily: 127.80382495236385,
                        unit: "mg",
                    },
                    {
                        label: "Potassium",
                        tag: "K",
                        schemaOrgTag: null,
                        total: 3223.805151798848,
                        hasRDI: true,
                        daily: 68.59159897444357,
                        unit: "mg",
                    },
                    {
                        label: "Iron",
                        tag: "FE",
                        schemaOrgTag: null,
                        total: 15.615565272995118,
                        hasRDI: true,
                        daily: 86.75314040552843,
                        unit: "mg",
                    },
                    {
                        label: "Zinc",
                        tag: "ZN",
                        schemaOrgTag: null,
                        total: 17.05631333149667,
                        hasRDI: true,
                        daily: 155.057393922697,
                        unit: "mg",
                    },
                    {
                        label: "Phosphorus",
                        tag: "P",
                        schemaOrgTag: null,
                        total: 2940.2734188495606,
                        hasRDI: true,
                        daily: 420.0390598356515,
                        unit: "mg",
                    },
                    {
                        label: "Vitamin A",
                        tag: "VITA_RAE",
                        schemaOrgTag: null,
                        total: 143.3799399,
                        hasRDI: true,
                        daily: 15.931104433333335,
                        unit: "µg",
                    },
                    {
                        label: "Vitamin C",
                        tag: "VITC",
                        schemaOrgTag: null,
                        total: 6.833999999910326,
                        hasRDI: true,
                        daily: 7.593333333233695,
                        unit: "mg",
                    },
                    {
                        label: "Thiamin (B1)",
                        tag: "THIA",
                        schemaOrgTag: null,
                        total: 0.8623261815994252,
                        hasRDI: true,
                        daily: 71.86051513328543,
                        unit: "mg",
                    },
                    {
                        label: "Riboflavin (B2)",
                        tag: "RIBF",
                        schemaOrgTag: null,
                        total: 0.583263361899684,
                        hasRDI: true,
                        daily: 44.86641245382184,
                        unit: "mg",
                    },
                    {
                        label: "Niacin (B3)",
                        tag: "NIA",
                        schemaOrgTag: null,
                        total: 14.138211319497989,
                        hasRDI: true,
                        daily: 88.36382074686243,
                        unit: "mg",
                    },
                    {
                        label: "Vitamin B6",
                        tag: "VITB6A",
                        schemaOrgTag: null,
                        total: 1.2981280532964505,
                        hasRDI: true,
                        daily: 99.85600409972696,
                        unit: "mg",
                    },
                    {
                        label: "Folate equivalent (total)",
                        tag: "FOLDFE",
                        schemaOrgTag: null,
                        total: 112.28647399999136,
                        hasRDI: true,
                        daily: 28.07161849999784,
                        unit: "µg",
                    },
                    {
                        label: "Folate (food)",
                        tag: "FOLFD",
                        schemaOrgTag: null,
                        total: 112.28647399999136,
                        hasRDI: false,
                        daily: 0,
                        unit: "µg",
                    },
                    {
                        label: "Folic acid",
                        tag: "FOLAC",
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: "µg",
                    },
                    {
                        label: "Vitamin B12",
                        tag: "VITB12",
                        schemaOrgTag: null,
                        total: 0.9968255030000002,
                        hasRDI: true,
                        daily: 41.53439595833334,
                        unit: "µg",
                    },
                    {
                        label: "Vitamin D",
                        tag: "VITD",
                        schemaOrgTag: null,
                        total: 0.39,
                        hasRDI: true,
                        daily: 2.6,
                        unit: "µg",
                    },
                    {
                        label: "Vitamin E",
                        tag: "TOCPHA",
                        schemaOrgTag: null,
                        total: 10.838261410999772,
                        hasRDI: true,
                        daily: 72.25507607333181,
                        unit: "mg",
                    },
                    {
                        label: "Vitamin K",
                        tag: "VITK1",
                        schemaOrgTag: null,
                        total: 158.01645583999513,
                        hasRDI: true,
                        daily: 131.6803798666626,
                        unit: "µg",
                    },
                    {
                        label: "Sugar alcohols",
                        tag: "Sugar.alcohol",
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: "g",
                    },
                    {
                        label: "Water",
                        tag: "WATER",
                        schemaOrgTag: null,
                        total: 506.3493606873317,
                        hasRDI: false,
                        daily: 0,
                        unit: "g",
                    },
                ],
            },
            _links: {
                self: {
                    href: "https://api.edamam.com/api/recipes/v2/753c111cf320a1e51d1ff36763c0d1c3?type=public&app_id=48be3615&app_key=cec90a0055ad0fcc0bb60ed6812eefc8",
                    title: "Self",
                },
            },
        },
        {
            recipe: {
                uri: "http://www.edamam.com/ontologies/edamam.owl#recipe_16bdd3f8a8c3536e66c80dca8f9e453c",
                label: "Lightened Up Shrimp Scampi Alfredo recipes",
                image: "https://edamam-product-images.s3.amazonaws.com/web-img/a36/a36a03f04c1e9ad7040a4eb5c40e136d?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQD58OvaS0k1th1eieaHIvo%2BArqS3ctqottfA67g9NJDiwIgfCjiMNbdDnrYyYvmLcgV93ti%2BWhrZtGP1qIO8XOqvrsq2wQI3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDA%2FsXz09Olo%2F8duILiqvBMnGnHQQDHJeTEaSlJjgs9FSxWnHZOfDij%2BgSaQdpBifykRxbIMgBoe%2F3O6cMSt504QCj6XfTWjQNt9eQyz2QF9dwxAJCp0PPFR1s0SiUmy%2FozQMeXyNNtoxE6NYN0EDf07cmfkdJLpUWw2ppdPBCXVBTwmsfJn%2Fh6JPWG9Ac8MadagCC40I22QBUFpKxfu%2BEVRGJXPFvwgM8dXocsStgASDigBBdD4KPdwmTt3nh37Ad%2FNFrXRyI5D4bqX4AxsqH4Iw%2By4LRJWdVFggV%2FzFKgPO6%2BAI6BMdugcEqjAS40w%2BbkxOY%2BNJl78Kh7ifecMkl8Fb%2Fnm6LYsldRpQsk1fK9r14D65%2BBEICt4b5UFg4QVcZAeSIm2xNLrLP63WZB1uply3A1GNXgxLPVPWAfz7O4obTy8xeQyPH46dbKWROz0WIurT2jiJITANLgvWWLl1gpgVo0Lv8%2BiLCt3Y05cf5XUFFg3IZJBCFKhGBy5WDRhONBBWOh3zFgnvtUmIiSxn3cSEUU8vBbMjgUPhdkHYKs%2BFDg%2BXhJlGpfEcdWuWzufnur5F9As7kapxYEXzwUEVNFbmMh8depJ%2FgiprNq6xwj0c%2BIO%2F7LGYVjeJ3IGG4jxDeFk%2FFktO93zk4maQnJ%2FgT23wi8Dnrrs%2F8a5Pi7m6qfrrIUr0K9V9UHX6LmQpcEHem7rJ%2BoM8MyH2x7XE6DBxoqQN3bGfY%2FSccYsScLlpFGLCr%2BSuvUX%2FcR7Me3HYKFEwj4G7lwY6qQF3%2FMB1mRqpoEQJ3tycVR%2Bdy4x4ixzjVLs%2B0uHjiI9I209eYWcOouy%2B9A2bGrszT2wjns%2Fn3u9W62EsgSoV%2FgNZMRQjkLtz2tuRGa9ZrHwIa0yAW7x9NKA%2BK%2BYSvIr%2FILrxbQvgs2b%2B8L8bFUiHl%2FFxzTXIFhVda0DKdY%2FUBVNxbNafHk6q8cCvC2J%2FiTsYlexx19skpkvx%2F6VkzBmzgvZzDeJKOCSP9i%2BA&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220806T200841Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFE64WOM3J%2F20220806%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=8a438e6075d9c35d02930689230ef3fdab96e7ef1e0fea72562b7cf2cfe072e2",
                images: {
                    THUMBNAIL: {
                        url: "https://edamam-product-images.s3.amazonaws.com/web-img/a36/a36a03f04c1e9ad7040a4eb5c40e136d-s?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQD58OvaS0k1th1eieaHIvo%2BArqS3ctqottfA67g9NJDiwIgfCjiMNbdDnrYyYvmLcgV93ti%2BWhrZtGP1qIO8XOqvrsq2wQI3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDA%2FsXz09Olo%2F8duILiqvBMnGnHQQDHJeTEaSlJjgs9FSxWnHZOfDij%2BgSaQdpBifykRxbIMgBoe%2F3O6cMSt504QCj6XfTWjQNt9eQyz2QF9dwxAJCp0PPFR1s0SiUmy%2FozQMeXyNNtoxE6NYN0EDf07cmfkdJLpUWw2ppdPBCXVBTwmsfJn%2Fh6JPWG9Ac8MadagCC40I22QBUFpKxfu%2BEVRGJXPFvwgM8dXocsStgASDigBBdD4KPdwmTt3nh37Ad%2FNFrXRyI5D4bqX4AxsqH4Iw%2By4LRJWdVFggV%2FzFKgPO6%2BAI6BMdugcEqjAS40w%2BbkxOY%2BNJl78Kh7ifecMkl8Fb%2Fnm6LYsldRpQsk1fK9r14D65%2BBEICt4b5UFg4QVcZAeSIm2xNLrLP63WZB1uply3A1GNXgxLPVPWAfz7O4obTy8xeQyPH46dbKWROz0WIurT2jiJITANLgvWWLl1gpgVo0Lv8%2BiLCt3Y05cf5XUFFg3IZJBCFKhGBy5WDRhONBBWOh3zFgnvtUmIiSxn3cSEUU8vBbMjgUPhdkHYKs%2BFDg%2BXhJlGpfEcdWuWzufnur5F9As7kapxYEXzwUEVNFbmMh8depJ%2FgiprNq6xwj0c%2BIO%2F7LGYVjeJ3IGG4jxDeFk%2FFktO93zk4maQnJ%2FgT23wi8Dnrrs%2F8a5Pi7m6qfrrIUr0K9V9UHX6LmQpcEHem7rJ%2BoM8MyH2x7XE6DBxoqQN3bGfY%2FSccYsScLlpFGLCr%2BSuvUX%2FcR7Me3HYKFEwj4G7lwY6qQF3%2FMB1mRqpoEQJ3tycVR%2Bdy4x4ixzjVLs%2B0uHjiI9I209eYWcOouy%2B9A2bGrszT2wjns%2Fn3u9W62EsgSoV%2FgNZMRQjkLtz2tuRGa9ZrHwIa0yAW7x9NKA%2BK%2BYSvIr%2FILrxbQvgs2b%2B8L8bFUiHl%2FFxzTXIFhVda0DKdY%2FUBVNxbNafHk6q8cCvC2J%2FiTsYlexx19skpkvx%2F6VkzBmzgvZzDeJKOCSP9i%2BA&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220806T200841Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFE64WOM3J%2F20220806%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7084c8f7359920900a51797e2df6064a30622e80c781ce1c38dde0fc8430fcfd",
                        width: 100,
                        height: 100,
                    },
                    SMALL: {
                        url: "https://edamam-product-images.s3.amazonaws.com/web-img/a36/a36a03f04c1e9ad7040a4eb5c40e136d-m?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQD58OvaS0k1th1eieaHIvo%2BArqS3ctqottfA67g9NJDiwIgfCjiMNbdDnrYyYvmLcgV93ti%2BWhrZtGP1qIO8XOqvrsq2wQI3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDA%2FsXz09Olo%2F8duILiqvBMnGnHQQDHJeTEaSlJjgs9FSxWnHZOfDij%2BgSaQdpBifykRxbIMgBoe%2F3O6cMSt504QCj6XfTWjQNt9eQyz2QF9dwxAJCp0PPFR1s0SiUmy%2FozQMeXyNNtoxE6NYN0EDf07cmfkdJLpUWw2ppdPBCXVBTwmsfJn%2Fh6JPWG9Ac8MadagCC40I22QBUFpKxfu%2BEVRGJXPFvwgM8dXocsStgASDigBBdD4KPdwmTt3nh37Ad%2FNFrXRyI5D4bqX4AxsqH4Iw%2By4LRJWdVFggV%2FzFKgPO6%2BAI6BMdugcEqjAS40w%2BbkxOY%2BNJl78Kh7ifecMkl8Fb%2Fnm6LYsldRpQsk1fK9r14D65%2BBEICt4b5UFg4QVcZAeSIm2xNLrLP63WZB1uply3A1GNXgxLPVPWAfz7O4obTy8xeQyPH46dbKWROz0WIurT2jiJITANLgvWWLl1gpgVo0Lv8%2BiLCt3Y05cf5XUFFg3IZJBCFKhGBy5WDRhONBBWOh3zFgnvtUmIiSxn3cSEUU8vBbMjgUPhdkHYKs%2BFDg%2BXhJlGpfEcdWuWzufnur5F9As7kapxYEXzwUEVNFbmMh8depJ%2FgiprNq6xwj0c%2BIO%2F7LGYVjeJ3IGG4jxDeFk%2FFktO93zk4maQnJ%2FgT23wi8Dnrrs%2F8a5Pi7m6qfrrIUr0K9V9UHX6LmQpcEHem7rJ%2BoM8MyH2x7XE6DBxoqQN3bGfY%2FSccYsScLlpFGLCr%2BSuvUX%2FcR7Me3HYKFEwj4G7lwY6qQF3%2FMB1mRqpoEQJ3tycVR%2Bdy4x4ixzjVLs%2B0uHjiI9I209eYWcOouy%2B9A2bGrszT2wjns%2Fn3u9W62EsgSoV%2FgNZMRQjkLtz2tuRGa9ZrHwIa0yAW7x9NKA%2BK%2BYSvIr%2FILrxbQvgs2b%2B8L8bFUiHl%2FFxzTXIFhVda0DKdY%2FUBVNxbNafHk6q8cCvC2J%2FiTsYlexx19skpkvx%2F6VkzBmzgvZzDeJKOCSP9i%2BA&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220806T200841Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFE64WOM3J%2F20220806%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=e88ca7054a2ee76bfc97fdd6136a2b8090b1c67cc8a924094db994d7d503be2a",
                        width: 200,
                        height: 200,
                    },
                    REGULAR: {
                        url: "https://edamam-product-images.s3.amazonaws.com/web-img/a36/a36a03f04c1e9ad7040a4eb5c40e136d?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQD58OvaS0k1th1eieaHIvo%2BArqS3ctqottfA67g9NJDiwIgfCjiMNbdDnrYyYvmLcgV93ti%2BWhrZtGP1qIO8XOqvrsq2wQI3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDA%2FsXz09Olo%2F8duILiqvBMnGnHQQDHJeTEaSlJjgs9FSxWnHZOfDij%2BgSaQdpBifykRxbIMgBoe%2F3O6cMSt504QCj6XfTWjQNt9eQyz2QF9dwxAJCp0PPFR1s0SiUmy%2FozQMeXyNNtoxE6NYN0EDf07cmfkdJLpUWw2ppdPBCXVBTwmsfJn%2Fh6JPWG9Ac8MadagCC40I22QBUFpKxfu%2BEVRGJXPFvwgM8dXocsStgASDigBBdD4KPdwmTt3nh37Ad%2FNFrXRyI5D4bqX4AxsqH4Iw%2By4LRJWdVFggV%2FzFKgPO6%2BAI6BMdugcEqjAS40w%2BbkxOY%2BNJl78Kh7ifecMkl8Fb%2Fnm6LYsldRpQsk1fK9r14D65%2BBEICt4b5UFg4QVcZAeSIm2xNLrLP63WZB1uply3A1GNXgxLPVPWAfz7O4obTy8xeQyPH46dbKWROz0WIurT2jiJITANLgvWWLl1gpgVo0Lv8%2BiLCt3Y05cf5XUFFg3IZJBCFKhGBy5WDRhONBBWOh3zFgnvtUmIiSxn3cSEUU8vBbMjgUPhdkHYKs%2BFDg%2BXhJlGpfEcdWuWzufnur5F9As7kapxYEXzwUEVNFbmMh8depJ%2FgiprNq6xwj0c%2BIO%2F7LGYVjeJ3IGG4jxDeFk%2FFktO93zk4maQnJ%2FgT23wi8Dnrrs%2F8a5Pi7m6qfrrIUr0K9V9UHX6LmQpcEHem7rJ%2BoM8MyH2x7XE6DBxoqQN3bGfY%2FSccYsScLlpFGLCr%2BSuvUX%2FcR7Me3HYKFEwj4G7lwY6qQF3%2FMB1mRqpoEQJ3tycVR%2Bdy4x4ixzjVLs%2B0uHjiI9I209eYWcOouy%2B9A2bGrszT2wjns%2Fn3u9W62EsgSoV%2FgNZMRQjkLtz2tuRGa9ZrHwIa0yAW7x9NKA%2BK%2BYSvIr%2FILrxbQvgs2b%2B8L8bFUiHl%2FFxzTXIFhVda0DKdY%2FUBVNxbNafHk6q8cCvC2J%2FiTsYlexx19skpkvx%2F6VkzBmzgvZzDeJKOCSP9i%2BA&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220806T200841Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFE64WOM3J%2F20220806%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=8a438e6075d9c35d02930689230ef3fdab96e7ef1e0fea72562b7cf2cfe072e2",
                        width: 300,
                        height: 300,
                    },
                },
                source: "wearychef.com",
                url: "http://wearychef.com/shrimp-scampi-alfredo/",
                shareAs:
                    "http://www.edamam.com/recipe/lightened-up-shrimp-scampi-alfredo-recipes-16bdd3f8a8c3536e66c80dca8f9e453c/shrimp+scampi+alfredo",
                yield: 4,
                dietLabels: [],
                healthLabels: [
                    "Pescatarian",
                    "Egg-Free",
                    "Peanut-Free",
                    "Tree-Nut-Free",
                    "Soy-Free",
                    "Fish-Free",
                    "Pork-Free",
                    "Red-Meat-Free",
                    "Celery-Free",
                    "Mustard-Free",
                    "Sesame-Free",
                    "Lupine-Free",
                    "Mollusk-Free",
                    "Alcohol-Free",
                ],
                cautions: ["Sulfites"],
                ingredientLines: [
                    "12 oz. pasta of your choice",
                    "1 tbsp. butter",
                    "1 tbsp. flour (all purpose, rice, or spelt flour all work)",
                    "1 c. milk",
                    "12 oz. package frozen SeaPak Light Shrimp Scampi",
                    "2 tbsp. grated parmesan cheese",
                ],
                ingredients: [
                    {
                        text: "12 oz. pasta of your choice",
                        quantity: 12,
                        measure: "ounce",
                        food: "pasta",
                        weight: 340.1942775,
                        foodCategory: "grains",
                        foodId: "food_a8hs60uayl5icia1qe8qoba1kwp8",
                        image: "https://www.edamam.com/food-img/296/296ff2b02ef3822928c3c923e22c7d19.jpg",
                    },
                    {
                        text: "1 tbsp. butter",
                        quantity: 1,
                        measure: "tablespoon",
                        food: "butter",
                        weight: 14.2,
                        foodCategory: "Dairy",
                        foodId: "food_awz3iefajbk1fwahq9logahmgltj",
                        image: "https://www.edamam.com/food-img/713/71397239b670d88c04faa8d05035cab4.jpg",
                    },
                    {
                        text: "1 tbsp. flour (all purpose, rice, or spelt flour all work)",
                        quantity: 1,
                        measure: "tablespoon",
                        food: "flour",
                        weight: 7.8124999998679145,
                        foodCategory: "grains",
                        foodId: "food_ahebfs0a985an4aubqaebbipra58",
                        image: "https://www.edamam.com/food-img/b4c/b4c739e76a6f2172b7ad49d0aa41d5aa.jpg",
                    },
                    {
                        text: "1 c. milk",
                        quantity: 1,
                        measure: "cup",
                        food: "milk",
                        weight: 244,
                        foodCategory: "Milk",
                        foodId: "food_b49rs1kaw0jktabzkg2vvanvvsis",
                        image: "https://www.edamam.com/food-img/7c9/7c9962acf83654a8d98ea6a2ade93735.jpg",
                    },
                    {
                        text: "12 oz. package frozen SeaPak Light Shrimp Scampi",
                        quantity: 12,
                        measure: "ounce",
                        food: "Shrimp",
                        weight: 340.1942775,
                        foodCategory: "seafood",
                        foodId: "food_b38bejhbq9loe2bbb7bnmbcpteft",
                        image: "https://www.edamam.com/food-img/ebe/ebe2888b894f48d19762e1d606db0206.jpg",
                    },
                    {
                        text: "2 tbsp. grated parmesan cheese",
                        quantity: 2,
                        measure: "tablespoon",
                        food: "parmesan cheese",
                        weight: 18.58828124968574,
                        foodCategory: "Cheese",
                        foodId: "food_a104ppxa06d3emb272fkcab3cugd",
                        image: "https://www.edamam.com/food-img/f58/f588658627c59d5041e4664119829aa9.jpg",
                    },
                ],
                calories: 1855.6162690482872,
                totalWeight: 964.9893362495537,
                totalTime: 15,
                cuisineType: ["italian"],
                mealType: ["lunch/dinner"],
                dishType: ["main course"],
                totalNutrients: {
                    ENERC_KCAL: {
                        label: "Energy",
                        quantity: 1855.6162690482872,
                        unit: "kcal",
                    },
                    FAT: {
                        label: "Fat",
                        quantity: 32.89843133979253,
                        unit: "g",
                    },
                    FASAT: {
                        label: "Saturated",
                        quantity: 16.737547541023226,
                        unit: "g",
                    },
                    FATRN: {
                        label: "Trans",
                        quantity: 0.5267109699499999,
                        unit: "g",
                    },
                    FAMS: {
                        label: "Monounsaturated",
                        quantity: 7.567452067713768,
                        unit: "g",
                    },
                    FAPU: {
                        label: "Polyunsaturated",
                        quantity: 3.968207789035166,
                        unit: "g",
                    },
                    CHOCDF: {
                        label: "Carbs",
                        quantity: 275.3996163406391,
                        unit: "g",
                    },
                    "CHOCDF.net": {
                        label: "Carbohydrates (net)",
                        quantity: 0,
                        unit: "g",
                    },
                    FIBTG: {
                        label: "Fiber",
                        quantity: 11.097154379996434,
                        unit: "g",
                    },
                    SUGAR: {
                        label: "Sugars",
                        quantity: 21.583507209247127,
                        unit: "g",
                    },
                    "SUGAR.added": {
                        label: "Sugars, added",
                        quantity: 0,
                        unit: "g",
                    },
                    PROCNT: {
                        label: "Protein",
                        quantity: 105.92081675049903,
                        unit: "g",
                    },
                    CHOLE: {
                        label: "Cholesterol",
                        quantity: 496.21482089978633,
                        unit: "mg",
                    },
                    NA: {
                        label: "Sodium",
                        quantity: 2308.324267295673,
                        unit: "mg",
                    },
                    CA: {
                        label: "Calcium",
                        quantity: 755.5308331212593,
                        unit: "mg",
                    },
                    MG: {
                        label: "Magnesium",
                        quantity: 289.7273018748326,
                        unit: "mg",
                    },
                    K: {
                        label: "Potassium",
                        quantity: 1494.0013661495695,
                        unit: "mg",
                    },
                    FE: {
                        label: "Iron",
                        quantity: 5.456803746495878,
                        unit: "mg",
                    },
                    ZN: {
                        label: "Zinc",
                        quantity: 9.578069038865435,
                        unit: "mg",
                    },
                    P: {
                        label: "Phosphorus",
                        quantity: 1818.8493934476764,
                        unit: "mg",
                    },
                    VITA_RAE: {
                        label: "Vitamin A",
                        quantity: 431.55065203684944,
                        unit: "µg",
                    },
                    VITC: {
                        label: "Vitamin C",
                        quantity: 0,
                        unit: "mg",
                    },
                    THIA: {
                        label: "Thiamin (B1)",
                        quantity: 0.503788134937219,
                        unit: "mg",
                    },
                    RIBF: {
                        label: "Riboflavin (B2)",
                        quantity: 0.7371718018739039,
                        unit: "mg",
                    },
                    NIA: {
                        label: "Niacin (B3)",
                        quantity: 12.203111463634997,
                        unit: "mg",
                    },
                    VITB6A: {
                        label: "Vitamin B6",
                        quantity: 1.139407496762156,
                        unit: "mg",
                    },
                    FOLDFE: {
                        label: "Folate equivalent (total)",
                        quantity: 141.83031236244366,
                        unit: "µg",
                    },
                    FOLFD: {
                        label: "Folate (food)",
                        quantity: 141.83031236244366,
                        unit: "µg",
                    },
                    FOLAC: {
                        label: "Folic acid",
                        quantity: 0,
                        unit: "µg",
                    },
                    VITB12: {
                        label: "Vitamin B12",
                        quantity: 5.12135585524623,
                        unit: "µg",
                    },
                    VITD: {
                        label: "Vitamin D",
                        quantity: 3.8181356837484293,
                        unit: "µg",
                    },
                    TOCPHA: {
                        label: "Vitamin E",
                        quantity: 5.410599886999229,
                        unit: "mg",
                    },
                    VITK1: {
                        label: "Vitamin K",
                        quantity: 3.4262153912442614,
                        unit: "µg",
                    },
                    "Sugar.alcohol": {
                        label: "Sugar alcohol",
                        quantity: 0,
                        unit: "g",
                    },
                    WATER: {
                        label: "Water",
                        quantity: 540.0107760376426,
                        unit: "g",
                    },
                },
                totalDaily: {
                    ENERC_KCAL: {
                        label: "Energy",
                        quantity: 92.78081345241436,
                        unit: "%",
                    },
                    FAT: {
                        label: "Fat",
                        quantity: 50.612971291988515,
                        unit: "%",
                    },
                    FASAT: {
                        label: "Saturated",
                        quantity: 83.68773770511612,
                        unit: "%",
                    },
                    CHOCDF: {
                        label: "Carbs",
                        quantity: 91.79987211354637,
                        unit: "%",
                    },
                    FIBTG: {
                        label: "Fiber",
                        quantity: 44.388617519985736,
                        unit: "%",
                    },
                    PROCNT: {
                        label: "Protein",
                        quantity: 211.84163350099806,
                        unit: "%",
                    },
                    CHOLE: {
                        label: "Cholesterol",
                        quantity: 165.4049402999288,
                        unit: "%",
                    },
                    NA: {
                        label: "Sodium",
                        quantity: 96.18017780398637,
                        unit: "%",
                    },
                    CA: {
                        label: "Calcium",
                        quantity: 75.55308331212593,
                        unit: "%",
                    },
                    MG: {
                        label: "Magnesium",
                        quantity: 68.9826909225792,
                        unit: "%",
                    },
                    K: {
                        label: "Potassium",
                        quantity: 31.78726310956531,
                        unit: "%",
                    },
                    FE: {
                        label: "Iron",
                        quantity: 30.31557636942155,
                        unit: "%",
                    },
                    ZN: {
                        label: "Zinc",
                        quantity: 87.07335489877667,
                        unit: "%",
                    },
                    P: {
                        label: "Phosphorus",
                        quantity: 259.83562763538237,
                        unit: "%",
                    },
                    VITA_RAE: {
                        label: "Vitamin A",
                        quantity: 47.950072448538826,
                        unit: "%",
                    },
                    VITC: {
                        label: "Vitamin C",
                        quantity: 0,
                        unit: "%",
                    },
                    THIA: {
                        label: "Thiamin (B1)",
                        quantity: 41.98234457810158,
                        unit: "%",
                    },
                    RIBF: {
                        label: "Riboflavin (B2)",
                        quantity: 56.70552322106953,
                        unit: "%",
                    },
                    NIA: {
                        label: "Niacin (B3)",
                        quantity: 76.26944664771872,
                        unit: "%",
                    },
                    VITB6A: {
                        label: "Vitamin B6",
                        quantity: 87.64673052016583,
                        unit: "%",
                    },
                    FOLDFE: {
                        label: "Folate equivalent (total)",
                        quantity: 35.457578090610916,
                        unit: "%",
                    },
                    VITB12: {
                        label: "Vitamin B12",
                        quantity: 213.38982730192626,
                        unit: "%",
                    },
                    VITD: {
                        label: "Vitamin D",
                        quantity: 25.454237891656195,
                        unit: "%",
                    },
                    TOCPHA: {
                        label: "Vitamin E",
                        quantity: 36.07066591332819,
                        unit: "%",
                    },
                    VITK1: {
                        label: "Vitamin K",
                        quantity: 2.855179492703551,
                        unit: "%",
                    },
                },
                digest: [
                    {
                        label: "Fat",
                        tag: "FAT",
                        schemaOrgTag: "fatContent",
                        total: 32.89843133979253,
                        hasRDI: true,
                        daily: 50.612971291988515,
                        unit: "g",
                        sub: [
                            {
                                label: "Saturated",
                                tag: "FASAT",
                                schemaOrgTag: "saturatedFatContent",
                                total: 16.737547541023226,
                                hasRDI: true,
                                daily: 83.68773770511612,
                                unit: "g",
                            },
                            {
                                label: "Trans",
                                tag: "FATRN",
                                schemaOrgTag: "transFatContent",
                                total: 0.5267109699499999,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                            {
                                label: "Monounsaturated",
                                tag: "FAMS",
                                schemaOrgTag: null,
                                total: 7.567452067713768,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                            {
                                label: "Polyunsaturated",
                                tag: "FAPU",
                                schemaOrgTag: null,
                                total: 3.968207789035166,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                        ],
                    },
                    {
                        label: "Carbs",
                        tag: "CHOCDF",
                        schemaOrgTag: "carbohydrateContent",
                        total: 275.3996163406391,
                        hasRDI: true,
                        daily: 91.79987211354637,
                        unit: "g",
                        sub: [
                            {
                                label: "Carbs (net)",
                                tag: "CHOCDF.net",
                                schemaOrgTag: null,
                                total: 0,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                            {
                                label: "Fiber",
                                tag: "FIBTG",
                                schemaOrgTag: "fiberContent",
                                total: 11.097154379996434,
                                hasRDI: true,
                                daily: 44.388617519985736,
                                unit: "g",
                            },
                            {
                                label: "Sugars",
                                tag: "SUGAR",
                                schemaOrgTag: "sugarContent",
                                total: 21.583507209247127,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                            {
                                label: "Sugars, added",
                                tag: "SUGAR.added",
                                schemaOrgTag: null,
                                total: 0,
                                hasRDI: false,
                                daily: 0,
                                unit: "g",
                            },
                        ],
                    },
                    {
                        label: "Protein",
                        tag: "PROCNT",
                        schemaOrgTag: "proteinContent",
                        total: 105.92081675049903,
                        hasRDI: true,
                        daily: 211.84163350099806,
                        unit: "g",
                    },
                    {
                        label: "Cholesterol",
                        tag: "CHOLE",
                        schemaOrgTag: "cholesterolContent",
                        total: 496.21482089978633,
                        hasRDI: true,
                        daily: 165.4049402999288,
                        unit: "mg",
                    },
                    {
                        label: "Sodium",
                        tag: "NA",
                        schemaOrgTag: "sodiumContent",
                        total: 2308.324267295673,
                        hasRDI: true,
                        daily: 96.18017780398637,
                        unit: "mg",
                    },
                    {
                        label: "Calcium",
                        tag: "CA",
                        schemaOrgTag: null,
                        total: 755.5308331212593,
                        hasRDI: true,
                        daily: 75.55308331212593,
                        unit: "mg",
                    },
                    {
                        label: "Magnesium",
                        tag: "MG",
                        schemaOrgTag: null,
                        total: 289.7273018748326,
                        hasRDI: true,
                        daily: 68.9826909225792,
                        unit: "mg",
                    },
                    {
                        label: "Potassium",
                        tag: "K",
                        schemaOrgTag: null,
                        total: 1494.0013661495695,
                        hasRDI: true,
                        daily: 31.78726310956531,
                        unit: "mg",
                    },
                    {
                        label: "Iron",
                        tag: "FE",
                        schemaOrgTag: null,
                        total: 5.456803746495878,
                        hasRDI: true,
                        daily: 30.31557636942155,
                        unit: "mg",
                    },
                    {
                        label: "Zinc",
                        tag: "ZN",
                        schemaOrgTag: null,
                        total: 9.578069038865435,
                        hasRDI: true,
                        daily: 87.07335489877667,
                        unit: "mg",
                    },
                    {
                        label: "Phosphorus",
                        tag: "P",
                        schemaOrgTag: null,
                        total: 1818.8493934476764,
                        hasRDI: true,
                        daily: 259.83562763538237,
                        unit: "mg",
                    },
                    {
                        label: "Vitamin A",
                        tag: "VITA_RAE",
                        schemaOrgTag: null,
                        total: 431.55065203684944,
                        hasRDI: true,
                        daily: 47.950072448538826,
                        unit: "µg",
                    },
                    {
                        label: "Vitamin C",
                        tag: "VITC",
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: true,
                        daily: 0,
                        unit: "mg",
                    },
                    {
                        label: "Thiamin (B1)",
                        tag: "THIA",
                        schemaOrgTag: null,
                        total: 0.503788134937219,
                        hasRDI: true,
                        daily: 41.98234457810158,
                        unit: "mg",
                    },
                    {
                        label: "Riboflavin (B2)",
                        tag: "RIBF",
                        schemaOrgTag: null,
                        total: 0.7371718018739039,
                        hasRDI: true,
                        daily: 56.70552322106953,
                        unit: "mg",
                    },
                    {
                        label: "Niacin (B3)",
                        tag: "NIA",
                        schemaOrgTag: null,
                        total: 12.203111463634997,
                        hasRDI: true,
                        daily: 76.26944664771872,
                        unit: "mg",
                    },
                    {
                        label: "Vitamin B6",
                        tag: "VITB6A",
                        schemaOrgTag: null,
                        total: 1.139407496762156,
                        hasRDI: true,
                        daily: 87.64673052016583,
                        unit: "mg",
                    },
                    {
                        label: "Folate equivalent (total)",
                        tag: "FOLDFE",
                        schemaOrgTag: null,
                        total: 141.83031236244366,
                        hasRDI: true,
                        daily: 35.457578090610916,
                        unit: "µg",
                    },
                    {
                        label: "Folate (food)",
                        tag: "FOLFD",
                        schemaOrgTag: null,
                        total: 141.83031236244366,
                        hasRDI: false,
                        daily: 0,
                        unit: "µg",
                    },
                    {
                        label: "Folic acid",
                        tag: "FOLAC",
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: "µg",
                    },
                    {
                        label: "Vitamin B12",
                        tag: "VITB12",
                        schemaOrgTag: null,
                        total: 5.12135585524623,
                        hasRDI: true,
                        daily: 213.38982730192626,
                        unit: "µg",
                    },
                    {
                        label: "Vitamin D",
                        tag: "VITD",
                        schemaOrgTag: null,
                        total: 3.8181356837484293,
                        hasRDI: true,
                        daily: 25.454237891656195,
                        unit: "µg",
                    },
                    {
                        label: "Vitamin E",
                        tag: "TOCPHA",
                        schemaOrgTag: null,
                        total: 5.410599886999229,
                        hasRDI: true,
                        daily: 36.07066591332819,
                        unit: "mg",
                    },
                    {
                        label: "Vitamin K",
                        tag: "VITK1",
                        schemaOrgTag: null,
                        total: 3.4262153912442614,
                        hasRDI: true,
                        daily: 2.855179492703551,
                        unit: "µg",
                    },
                    {
                        label: "Sugar alcohols",
                        tag: "Sugar.alcohol",
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: "g",
                    },
                    {
                        label: "Water",
                        tag: "WATER",
                        schemaOrgTag: null,
                        total: 540.0107760376426,
                        hasRDI: false,
                        daily: 0,
                        unit: "g",
                    },
                ],
            },
            _links: {
                self: {
                    href: "https://api.edamam.com/api/recipes/v2/16bdd3f8a8c3536e66c80dca8f9e453c?type=public&app_id=48be3615&app_key=cec90a0055ad0fcc0bb60ed6812eefc8",
                    title: "Self",
                },
            },
        },
    ],
}
